# Generated by Django 2.2.7 on 2019-11-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsmeta',
            name='nom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
