# Generated by Django 2.2.7 on 2019-11-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_modelsmeta_nom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelsMeta',
        ),
    ]
