# Generated by Django 2.2.7 on 2019-11-07 15:04

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metas', '0003_delete_modelsmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
