# Generated by Django 2.2.7 on 2019-11-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0006_auto_20191109_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metamodel',
            old_name='description',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='metamodel',
            old_name='title',
            new_name='menu',
        ),
    ]
