# Generated by Django 2.2.7 on 2019-11-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0007_auto_20191109_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetaModel',
            new_name='MetasModels',
        ),
    ]
