# Generated by Django 2.2.7 on 2019-11-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0008_auto_20191109_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metasmodels',
            old_name='detail',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='metasmodels',
            old_name='menu',
            new_name='title',
        ),
    ]
