# Generated by Django 2.2.7 on 2019-11-10 23:31

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0010_metasmodels_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abstract', models.TextField()),
            ],
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
