# Generated by Django 2.2.7 on 2019-11-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('metas', '0012_auto_20191111_0025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='MetaSite',
        ),
    ]
