# Generated by Django 2.2.7 on 2019-11-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0013_auto_20191111_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaSite',
        ),
    ]
