# Generated by Django 2.2.7 on 2019-11-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0014_delete_metasite'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasmodels',
            name='url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
